version: 2

container_config: &container_config
  working_directory: ~/project
  docker:
    - image: circleci/node:8.11.3

jobs:
  test:
    <<: *container_config
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Lint check
          command: npx eslint src

  upload:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: create setting files
          command: |
            echo $CRASP_AUTH > ~/.clasprc.json
            echo $CRASP_CONFIG > .clasp.json
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: upload files
          command: npx clasp push

workflows:
  version: 2
  test-and-upload:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
      - upload:
          requires:
            - test
          filters:
            branches:
              only: master
